[workspace]
members = [
    "engine",
    "engine/vault",
    "engine/primitives",
    "engine/random",
    "engine/crypto",
    "engine/snapshot",
    "engine/communication"
]
exclude = [
  "products/commandline",
  "products/desktop",
  "products/SHaaS",
  "client",
]
